### ISSUE TITLE
Copying content from a 10.2.2 Portal to a 10.3 Portal fails

### ISSUE THREAD

**Issue by bstayeresri** [Esri/ago-assistant#82] opened 2015-04-30 16:10 UTC
I'm trying to copy content from a 10.2.2 Portal to a 10.3 Portal. Every time I drag something over, it fails, saying, "Copying failed! 'type' and 'title' property required." This happens with ArcGIS Server map services, web maps, and external (not hosted) applications.

**Comment by ecaldwell** [comment] 2015-04-30 23:30
Are you able to copy the source items anywhere else successfully (like ArcGIS Online)?

**Comment by bstayeresri** [comment] 2015-05-01 14:13
Yes, I can successfully copy from the 10.2.2 Portal to ArcGIS Online. I can also successfully copy content from ArcGIS Online to the 10.3 Portal.

**Comment by ecaldwell** [comment] 2015-05-13 14:22
Tested and it's working now. Closing this one out since we can't reproduce. Maybe the [tubes were filled](http://en.wikipedia.org/wiki/Series_of_tubes). :wink:

**Closed by ecaldwell** 2015-05-13 14:22 UTC
