### ISSUE TITLE
Issues with Signing in to ArcGIS Portal

### ISSUE THREAD

**Issue by MScott-GIS** [Esri/ago-assistant#186] opened 2017-05-26 09:18 UTC
Hello, 

Our organisations ArcGIS Portal is internally facing and within a DMZ and all users are added based on IWA - I have been experiencing issues trying to sign in to the Portal using the ArcGIS Online Assistant.

When I put in the URL of the Portal and my username and password on the Portal, the "Logging In..." continues for a long period of time and does not log in. When looking at the Inspect element and running the Log On button, the Console gives the following error back:

Unable to get property 'generateToken' of undefined or null reference. 

I was wondering is this maybe because our Portal is not public facing - or is it possibly another issue?

**Comment by slibby** [comment] 2017-07-30 17:29
@MScott-GIS can you post a .HAR from Fiddler or console Network Tab log of the sequence of requests that your browser sends to the Portal before failing?

**Comment by slibby** [comment] 2017-09-26 23:03
@MScott-GIS have you tried this workflow since we made some updates to the login process on the hosted ago-assistant app? I would like to know if you're still having these problemsor we could close the issue?

**Comment by MScott-GIS** [comment] 2017-09-27 09:08
@slibby Thanks for your response - unfortunately we are not allowed to use Fiddler in our organisation - otherwise I would send those to you. However, the changes you have made to the PKI/IWA Login have made a difference to a degree. 

I can still not sign in to that original portal that we have been facing (10.3.1), but we have anew portal site that is 10.5.1 and it works perfectly with that. So I feel that it may be an isolated issue with our old portal site - unfortunately there were other issues with that site before, so I wouldn't say that there is anything wrong with your web tool! 

Thank you for investigating! :)

**Comment by ecaldwell** [comment] 2017-09-27 13:07
Thanks for the follow up @MScott-GIS and @slibby. Closing this one out as not reproducible.

**Closed by ecaldwell** 2017-09-27 13:07 UTC
Labels: not reproducible
