### ISSUE TITLE
Can't use with public account

### ISSUE THREAD

**Issue by glazou** [Esri/ago-assistant#130] opened 2016-04-27 01:50 UTC
With a 2 years old public account as well as a newly created public account (by entering information manually - not using social platforms) and the assistant is not finding any content

![image](https://cloud.githubusercontent.com/assets/994078/14839443/c4825a22-0bdf-11e6-995d-a21dc0856bce.png)

![image](https://cloud.githubusercontent.com/assets/994078/14839421/9be66a4a-0bdf-11e6-8603-66b451799062.png)

The request are made to funny URL

![image](https://cloud.githubusercontent.com/assets/994078/14839437/b0f94e20-0bdf-11e6-9bcd-61b34b4b7531.png)

Thanks

**Comment by ecaldwell** [comment] 2016-04-29 19:37
Whoops. I know exactly what the problem is. When I made the changes for #129 I forgot that there could be free accounts that wouldn't have an org name. I'll add a little test to default to `https://www.arcgis.com` if they're not a portal AND there's no org name. Thanks for reporting this!

**Comment by ecaldwell** [comment] 2016-05-03 04:25
Fixed with #132. Updates should be live now. Let me know if you see any additional issues with it. Thanks again!

**Closed by ecaldwell** 2016-05-03 04:25 UTC
Labels: bug
