### ISSUE TITLE
JSON editor hangs / refuses save on specific item json

### ISSUE THREAD

**Issue by powerslave** [Esri/ago-assistant#143] opened 2016-07-31 14:23 UTC
Different issues in Chrome, IE and Firefox, probably same root cause.
webscene Item Pro_512WGS84: http://www.arcgis.com/home/item.html?id=23ea2c5ffdae43fdbd571ff79952114a
#### Chrome:
- On the above item, _View an Item's JSON_
- In data section, enable edit
- Change arbitrary character (e.g. add a linebreak)  

-> browser hangs and eventually shows "kill unresponsive page" dialog
#### Firefox
- On the above item, _View an Item's JSON_
- In data section, enable edit
- Add a linebreak  

-> Save icon turns red, (invalid JSON) but it _is_ still valid. (no console errors)
#### IE 11
- On the above item, _View an Item's JSON_
- In data section, enable edit
- Modify json, hit Save  

-> save doesn't do anything. N(o console errors)

The item in question holds a webscene JSON. The JSON is not very large, it does however hold a heavy property value (a base64-encoded image string) in presentation.slide.thumbnail

``` js
"presentation": {
  "slides": [{
    "thumbnail": {
       "url": "data:image/jpeg;base64,Qk02bAAAAAAAADYAAAA..."
...
```

(full json here:
http://www.arcgis.com/sharing/rest/content/items/23ea2c5ffdae43fdbd571ff79952114a/data?f=pjson)

Suspicion is  the Editor's JSON parser / syntax checker is thrown off by this.

**Comment by powerslave** [comment] 2016-07-31 14:54
suspicion (at least partially) confirmed: same item without the heavy base64 string behaves as expected, no problem on editing / saving json in Chrome.
http://devext.arcgis.com/home/item.html?id=cf8edb1286e443728f0d80f414c111a6

**Comment by ecaldwell** [comment] 2016-08-01 20:55
Maybe a [web worker](https://github.com/isagalaev/highlight.js#web-workers) would alleviate this issue.

**Comment by nheminger** [comment] 2016-08-01 21:25
@ecaldwell I like it :+1:

**Comment by powerslave** [comment] 2016-08-02 08:23
Web workers shouldn't be necessary.

There are several json synatx checkers around that handle parsing the json in question with no problems, e.g. http://www.jsoneditoronline.org/, http://jsonschemalint.com/, http://www.jsonschemavalidator.net/
None of those use web workers.

I suspect the JSON module used in ago-assistant has a bug, or an implementation that cannot cope with the long string.

**Comment by rwmajor2** [comment] 2017-03-11 02:24
@powerslave I just updated Chrome to 57.0.2987.98 and it appears to no longer happen.  I was able to replicate this behavior earlier on all items, not just items with base64 encoded string.  I am still seeing strange behavior in Firefox and IE.  There is no reason that this should be failing like it is on JSON.parse().  Perhaps this is some JS bug that was introduced and now Chrome (at a minimum) has fixed?

**Comment by hogpilot** [comment] 2017-10-19 19:37
Possibly fixed with #214?  I'm unable to test as the above referenced items are not accessible currently.

**Comment by andreasulmer** [comment] 2017-10-21 03:32
here's another heavy-ish item, with lengthy base64 image strings:
http://www.arcgis.com/home/item.html?id=a9682bdb291b4245be3c39a04bf5583b

*  :+1: I tested with **Chrome** and **FF**: can't repro, no issues, seems fixed
* ❓ Tried with **Edge** as well, but I was unable to sign in. Somehow that OAuth redirection does not properly redirect back for me, but could be I'm operating this the wrong way.

Maybe you could have a look there?

**Comment by slibby** [comment] 2018-03-15 01:37
I just checked this and was unable to reproduce - we switched to a new JSON rendering framework so hopefully that has helped. I'm going to close this unless someone can repro, in which case we can reopen and investigate.

**Closed by slibby** 2018-03-15 01:37 UTC
Labels: bug

**Comment by andreasulmer** [comment] 2018-03-15 16:56
👍 did a quick test on **Edge** as well with the [heavy scene](http://www.arcgis.com/home/item.html?id=a9682bdb291b4245be3c39a04bf5583b), all works fine for me (editor is a bit sluggish, but still interactive enough)
